name: Build Gridly C# SDK

on:
  push:
    branches:
      - 'GRIDLY**'
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - 'GRIDLY**'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        framework: [net48, net8.0, net9.0]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x

      - name: Restore solution
        run: dotnet restore src/Com.Gridly/Com.Gridly.csproj

      - name: Build (${{ matrix.framework }})
        run: dotnet build --configuration Release --no-restore src/Com.Gridly/Com.Gridly.csproj -f ${{ matrix.framework }}

      - name: Run tests (${{ matrix.framework }})
        run: dotnet test --configuration Release --no-build --verbosity normal src/Com.Gridly.Test/Com.Gridly.Test.csproj -f ${{ matrix.framework }}

      - name: Publish (${{ matrix.framework }})
        run: dotnet publish src/Com.Gridly/Com.Gridly.csproj -c Release -f ${{ matrix.framework }} -o ./publish/${{ matrix.framework }}

      - name: Archive artifact (${{ matrix.framework }})
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.framework }}
          path: ./publish/${{ matrix.framework }}
          retention-days: 7